### ISSUE TITLE
Does Swagger Node only produce raw doc endpoints? Does it generate a UI endpoint as well?

### ISSUE THREAD

**Issue by behrangsa** [swagger-api/swagger-node#234] opened 2015-06-25 01:28 UTC
Hi,

Does Swagger Node produce a URL such as `/swagger/ui/index.html` to serve the HTML human readable documentation?

Or do we have to manually install swagger-ui and configure it?

**Comment by theganyo** [comment] 2015-06-25 22:12
We do intend to support this, but unfortunately you'll have to install and configure it manually for now.

**Comment by mohsen1** [comment] 2015-06-25 22:14
You can look at [this file](https://github.com/noahdietz/swagger-travel-groups/blob/master/travel-groups/swagger-ui-router.js) as a sample of doing it manually.

**Comment by behrangsa** [comment] 2015-06-26 01:42
@theganyo no worries. Looking forward to it :smiley: 

@mohsen1 I just installed swagger-ui and configured my Express app to serve it via static middleware. But ideally I was looking for it to be configured automatically.

**Comment by theganyo** [comment] 2015-10-05 23:22
Closing as duplicate of #4.

**Closed** 2015-10-05 23:22 UTC
